Omit direct write access to HttpResponseWriter
HUK-COBURG/openapirouter pull request #11
Opened 2021-06-18 11:22 UTC by crissi98

fixes sonar findings: https://lift.sonatype.com/result/HUK-COBURG/openapirouter/01F8F9RTWEDVSQYXP9GS4HCY6B?tab=results

2021-06-18 11:55 UTC, crissi98 commented on response.go
> +		_, err = io.WriteString(writer, data)
@Lift-def ignore
a plain text response should be written so no html escaping is necessary

2021-06-22 18:22 UTC, cniweb commented on response.go
> +		_, err = io.WriteString(writer, data)
@Lift-dev ignore

2021-06-22 18:26 UTC, cniweb requested changes

2021-06-22 18:26 UTC, cniweb commented on response.go
> +			_, err = io.WriteString(writer, "")
@Lift-dev ignore

2021-06-22 18:26 UTC, cniweb commented on response.go
> +	"io"
@Lift-dev ignore

2021-06-30 22:32 UTC, svnhof commented
@crissi98 Since we only work with JSON here I see no need for the change

2021-07-01 07:40 UTC, crissi98 commented
@svnhof You are right. And since this PR does not fix the issue, so I am closing it.

2021-07-01 07:40 UTC, closed without merging